# config/routes/test_auth_ui.yaml
# TEMPORARY - DELETE after backend implementation

test_auth_login:
    path: /test-auth/login
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'security/login.html.twig'

test_auth_register:
    path: /test-auth/register
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'registration/register.html.twig'

test_auth_reset_request:
    path: /test-auth/reset-request
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'reset_password/request.html.twig'

test_auth_reset_form:
    path: /test-auth/reset-form
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'reset_password/reset.html.twig'

# Create aliases for expected route names
app_login:
    path: /login
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'security/login.html.twig'

app_register:
    path: /register
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'registration/register.html.twig'

app_reset_password_request:
    path: /reset-password/request
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'reset_password/request.html.twig'

app_reset_password_reset:
    path: /reset-password/reset/test-token
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'reset_password/reset.html.twig'

# Dummy routes for navigation
app_generate:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'generate/index.html.twig'

app_sets:
    path: /sets
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'sets/list.html.twig'

app_logout:
    path: /logout
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'security/login.html.twig'
